[project]
name = "sict-bimini"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain-core>=1.0.5",
    "langchain-ollama>=1.0.0",
    "openpyxl>=3.1.5",
    "pymilvus[milvus-lite]>=2.6.3",
    "sentence-transformers>=5.1.2",
    "torch>=2.9.1",
]
